name: Arduino nRF52

on:
  push:
  pull_request:
    types: [opened, reopened]

env:
  # convenient variable used multiple times
  SKETCHES_REPORTS: sketches-reports

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install clang-format
        run: sudo apt-get install clang-format-12

      - name: Install linter python package
        run: python3 -m pip install cpp-linter
      - name: run linter as a python package
        id: linter
        run: |
          cpp-linter \
          --version=12 \
          --style=file \
          --tidy-checks='-*' \
          --files-changed-only='False' \
          --extensions=ino \
          --ignore='examples/old_backups'
      - name: Linter checks failed?
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
  build:
    needs: check_formatting
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        fqbn:
          # - "arduino:mbed:nano33ble"
          - "adafruit:nrf52:feather52840"
          # - "adafruit:nrf52:feather52832"  # Not compatible with sample_ed()
        # By default, don't generate size deltas data.
        enable-deltas-report: 
          - false
        # Generate size deltas data for this board
        include:
          - fqbn: Seeeduino:nrf52:xiaonRF52840
            enable-deltas-report: true
          - fqbn: adafruit:nrf52:itsybitsy52840
            enable-deltas-report: true
 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: sketch reports
        if: matrix.enable-deltas-report
        id: delta-report-name
        run: >-
          echo "report-name=${{ matrix.fqbn }}" | tr : - >> "$GITHUB_OUTPUT"

      # the adafruit Arduino nRF52 core needs the adafruit-nrfutil py pkg
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install adafruit-nrfutil
        run: pip3 install adafruit-nrfutil

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          sketch-paths: |
            - examples/GettingStarted
          fqbn: ${{ matrix.fqbn }}
          enable-deltas-report: ${{ matrix.enable-deltas-report }}
          sketches-report-path: ${{ env.SKETCHES_REPORTS }}
          # install earlphilhower's arduino-pico platform index
          platforms: |
            - name: adafruit:nrf52
              source-url: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
            - name: Seeeduino:nrf52
              source-url: https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
      
      # This step is needed to pass the size data to the report job 
      - name: Upload sketches report to workflow artifact
        if: ${{ matrix.enable-deltas-report }}
        uses: actions/upload-artifact@v4
        with:
          name: arduino-deltas-${{ steps.delta-report-name.outputs.report-name }}
          path: ${{ env.SKETCHES_REPORTS }}
  report:
    needs: [build]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Download sketches reports artifact
        uses: actions/download-artifact@v4
        with:
          pattern: arduino-deltas-*
          path: ${{ env.SKETCHES_REPORTS }}

      - uses: arduino/report-size-deltas@v1
        with:
          sketches-reports-source: ${{ env.SKETCHES_REPORTS }}
